/**
 * 🤖 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/dev/generate-tokens.mjs
 * 
 * This file provides type-safe access to your CSS variables.
 * Use these in your style objects or inline styles.
 */

export const tokens = {
  "color": {
    "navy": {
      "50": "var(--color-navy-50)",
      "100": "var(--color-navy-100)",
      "200": "var(--color-navy-200)",
      "300": "var(--color-navy-300)",
      "400": "var(--color-navy-400)",
      "500": "var(--color-navy-500)",
      "600": "var(--color-navy-600)",
      "700": "var(--color-navy-700)",
      "800": "var(--color-navy-800)",
      "900": "var(--color-navy-900)",
      "DEFAULT": "var(--color-navy)"
    },
    "silver": {
      "100": "var(--color-silver-100)",
      "200": "var(--color-silver-200)",
      "300": "var(--color-silver-300)",
      "400": "var(--color-silver-400)",
      "500": "var(--color-silver-500)",
      "600": "var(--color-silver-600)",
      "700": "var(--color-silver-700)",
      "800": "var(--color-silver-800)",
      "900": "var(--color-silver-900)",
      "DEFAULT": "var(--color-silver)"
    },
    "off": {
      "white": "var(--color-off-white)"
    },
    "accent": {
      "orange": {
        "50": "var(--color-accent-orange-50)",
        "100": "var(--color-accent-orange-100)",
        "200": "var(--color-accent-orange-200)",
        "300": "var(--color-accent-orange-300)",
        "400": "var(--color-accent-orange-400)",
        "500": "var(--color-accent-orange-500)",
        "600": "var(--color-accent-orange-600)",
        "700": "var(--color-accent-orange-700)",
        "800": "var(--color-accent-orange-800)",
        "900": "var(--color-accent-orange-900)",
        "950": "var(--color-accent-orange-950)",
        "DEFAULT": "var(--color-accent-orange)"
      },
      "green": {
        "50": "var(--color-accent-green-50)",
        "100": "var(--color-accent-green-100)",
        "200": "var(--color-accent-green-200)",
        "300": "var(--color-accent-green-300)",
        "400": "var(--color-accent-green-400)",
        "500": "var(--color-accent-green-500)",
        "600": "var(--color-accent-green-600)",
        "700": "var(--color-accent-green-700)",
        "800": "var(--color-accent-green-800)",
        "900": "var(--color-accent-green-900)",
        "950": "var(--color-accent-green-950)",
        "DEFAULT": "var(--color-accent-green)"
      },
      "purple": {
        "50": "var(--color-accent-purple-50)",
        "100": "var(--color-accent-purple-100)",
        "200": "var(--color-accent-purple-200)",
        "300": "var(--color-accent-purple-300)",
        "400": "var(--color-accent-purple-400)",
        "500": "var(--color-accent-purple-500)",
        "600": "var(--color-accent-purple-600)",
        "700": "var(--color-accent-purple-700)",
        "800": "var(--color-accent-purple-800)",
        "900": "var(--color-accent-purple-900)",
        "950": "var(--color-accent-purple-950)",
        "DEFAULT": "var(--color-accent-purple)"
      },
      "pink": {
        "50": "var(--color-accent-pink-50)",
        "100": "var(--color-accent-pink-100)",
        "200": "var(--color-accent-pink-200)",
        "300": "var(--color-accent-pink-300)",
        "400": "var(--color-accent-pink-400)",
        "500": "var(--color-accent-pink-500)",
        "600": "var(--color-accent-pink-600)",
        "700": "var(--color-accent-pink-700)",
        "800": "var(--color-accent-pink-800)",
        "900": "var(--color-accent-pink-900)",
        "950": "var(--color-accent-pink-950)",
        "DEFAULT": "var(--color-accent-pink)"
      },
      "amber": {
        "50": "var(--color-accent-amber-50)",
        "100": "var(--color-accent-amber-100)",
        "200": "var(--color-accent-amber-200)",
        "300": "var(--color-accent-amber-300)",
        "400": "var(--color-accent-amber-400)",
        "500": "var(--color-accent-amber-500)",
        "600": "var(--color-accent-amber-600)",
        "700": "var(--color-accent-amber-700)",
        "800": "var(--color-accent-amber-800)",
        "900": "var(--color-accent-amber-900)",
        "950": "var(--color-accent-amber-950)",
        "DEFAULT": "var(--color-accent-amber)"
      },
      "yellow": "var(--color-accent-yellow)",
      "red": {
        "50": "var(--color-accent-red-50)",
        "100": "var(--color-accent-red-100)",
        "200": "var(--color-accent-red-200)",
        "300": "var(--color-accent-red-300)",
        "400": "var(--color-accent-red-400)",
        "500": "var(--color-accent-red-500)",
        "600": "var(--color-accent-red-600)",
        "700": "var(--color-accent-red-700)",
        "800": "var(--color-accent-red-800)",
        "900": "var(--color-accent-red-900)",
        "950": "var(--color-accent-red-950)",
        "DEFAULT": "var(--color-accent-red)"
      },
      "blue": {
        "50": "var(--color-accent-blue-50)",
        "100": "var(--color-accent-blue-100)",
        "200": "var(--color-accent-blue-200)",
        "300": "var(--color-accent-blue-300)",
        "400": "var(--color-accent-blue-400)",
        "500": "var(--color-accent-blue-500)",
        "600": "var(--color-accent-blue-600)",
        "700": "var(--color-accent-blue-700)",
        "800": "var(--color-accent-blue-800)",
        "900": "var(--color-accent-blue-900)",
        "950": "var(--color-accent-blue-950)",
        "DEFAULT": "var(--color-accent-blue)"
      },
      "cyan": {
        "50": "var(--color-accent-cyan-50)",
        "100": "var(--color-accent-cyan-100)",
        "200": "var(--color-accent-cyan-200)",
        "300": "var(--color-accent-cyan-300)",
        "400": "var(--color-accent-cyan-400)",
        "500": "var(--color-accent-cyan-500)",
        "600": "var(--color-accent-cyan-600)",
        "700": "var(--color-accent-cyan-700)",
        "800": "var(--color-accent-cyan-800)",
        "900": "var(--color-accent-cyan-900)",
        "950": "var(--color-accent-cyan-950)",
        "DEFAULT": "var(--color-accent-cyan)"
      },
      "lime": {
        "50": "var(--color-accent-lime-50)",
        "100": "var(--color-accent-lime-100)",
        "200": "var(--color-accent-lime-200)",
        "300": "var(--color-accent-lime-300)",
        "400": "var(--color-accent-lime-400)",
        "500": "var(--color-accent-lime-500)",
        "600": "var(--color-accent-lime-600)",
        "700": "var(--color-accent-lime-700)",
        "800": "var(--color-accent-lime-800)",
        "900": "var(--color-accent-lime-900)",
        "950": "var(--color-accent-lime-950)",
        "DEFAULT": "var(--color-accent-lime)"
      },
      "indigo": {
        "50": "var(--color-accent-indigo-50)",
        "100": "var(--color-accent-indigo-100)",
        "200": "var(--color-accent-indigo-200)",
        "300": "var(--color-accent-indigo-300)",
        "400": "var(--color-accent-indigo-400)",
        "500": "var(--color-accent-indigo-500)",
        "600": "var(--color-accent-indigo-600)",
        "700": "var(--color-accent-indigo-700)",
        "800": "var(--color-accent-indigo-800)",
        "900": "var(--color-accent-indigo-900)",
        "950": "var(--color-accent-indigo-950)",
        "DEFAULT": "var(--color-accent-indigo)"
      }
    },
    "success": {
      "lightest": "var(--color-success-lightest)",
      "lighter": "var(--color-success-lighter)",
      "light": "var(--color-success-light)",
      "DEFAULT": "var(--color-success)",
      "dark": "var(--color-success-dark)",
      "darker": "var(--color-success-darker)",
      "darkest": "var(--color-success-darkest)"
    },
    "warning": {
      "lightest": "var(--color-warning-lightest)",
      "lighter": "var(--color-warning-lighter)",
      "light": "var(--color-warning-light)",
      "DEFAULT": "var(--color-warning)",
      "dark": "var(--color-warning-dark)",
      "darker": "var(--color-warning-darker)",
      "darkest": "var(--color-warning-darkest)"
    },
    "error": {
      "lightest": "var(--color-error-lightest)",
      "lighter": "var(--color-error-lighter)",
      "light": "var(--color-error-light)",
      "DEFAULT": "var(--color-error)",
      "dark": "var(--color-error-dark)",
      "darker": "var(--color-error-darker)",
      "darkest": "var(--color-error-darkest)"
    },
    "info": {
      "lightest": "var(--color-info-lightest)",
      "lighter": "var(--color-info-lighter)",
      "light": "var(--color-info-light)",
      "DEFAULT": "var(--color-info)",
      "dark": "var(--color-info-dark)",
      "darker": "var(--color-info-darker)",
      "darkest": "var(--color-info-darkest)"
    },
    "neutral": {
      "lightest": "var(--color-neutral-lightest)",
      "lighter": "var(--color-neutral-lighter)",
      "light": "var(--color-neutral-light)",
      "DEFAULT": "var(--color-neutral)",
      "dark": "var(--color-neutral-dark)",
      "darker": "var(--color-neutral-darker)",
      "darkest": "var(--color-neutral-darkest)"
    },
    "interactive": {
      "primary": {
        "base": "var(--color-interactive-primary-base)",
        "hover": "var(--color-interactive-primary-hover)",
        "active": "var(--color-interactive-primary-active)",
        "disabled": "var(--color-interactive-primary-disabled)",
        "focus": "var(--color-interactive-primary-focus)"
      },
      "secondary": {
        "base": "var(--color-interactive-secondary-base)",
        "hover": "var(--color-interactive-secondary-hover)",
        "active": "var(--color-interactive-secondary-active)",
        "disabled": "var(--color-interactive-secondary-disabled)",
        "focus": "var(--color-interactive-secondary-focus)"
      },
      "success": {
        "base": "var(--color-interactive-success-base)",
        "hover": "var(--color-interactive-success-hover)",
        "active": "var(--color-interactive-success-active)",
        "disabled": "var(--color-interactive-success-disabled)",
        "focus": "var(--color-interactive-success-focus)"
      },
      "danger": {
        "base": "var(--color-interactive-danger-base)",
        "hover": "var(--color-interactive-danger-hover)",
        "active": "var(--color-interactive-danger-active)",
        "disabled": "var(--color-interactive-danger-disabled)",
        "focus": "var(--color-interactive-danger-focus)"
      },
      "ghost": {
        "base": "var(--color-interactive-ghost-base)",
        "hover": "var(--color-interactive-ghost-hover)",
        "active": "var(--color-interactive-ghost-active)",
        "disabled": "var(--color-interactive-ghost-disabled)",
        "focus": "var(--color-interactive-ghost-focus)"
      }
    },
    "text": {
      "primary": "var(--color-text-primary)",
      "secondary": "var(--color-text-secondary)",
      "tertiary": "var(--color-text-tertiary)",
      "inverse": "var(--color-text-inverse)",
      "accent": "var(--color-text-accent)"
    },
    "bg": {
      "primary": "var(--color-bg-primary)",
      "secondary": "var(--color-bg-secondary)",
      "tertiary": "var(--color-bg-tertiary)",
      "surface": "var(--color-bg-surface)",
      "overlay": "var(--color-bg-overlay)"
    },
    "border": {
      "primary": "var(--color-border-primary)",
      "secondary": "var(--color-border-secondary)",
      "accent": "var(--color-border-accent)",
      "focus": "var(--color-border-focus)"
    }
  },
  "font": {
    "family": {
      "primary": "var(--font-family-primary)",
      "heading": "var(--font-family-heading)",
      "display": "var(--font-family-display)"
    },
    "size": {
      "xs": "var(--font-size-xs)",
      "sm": "var(--font-size-sm)",
      "base": "var(--font-size-base)",
      "md": "var(--font-size-md)",
      "lg": "var(--font-size-lg)",
      "xl": "var(--font-size-xl)",
      "2xl": "var(--font-size-2xl)",
      "3xl": "var(--font-size-3xl)",
      "4xl": "var(--font-size-4xl)",
      "5xl": "var(--font-size-5xl)",
      "6xl": "var(--font-size-6xl)",
      "7xl": "var(--font-size-7xl)",
      "8xl": "var(--font-size-8xl)",
      "9xl": "var(--font-size-9xl)",
      "fluid": {
        "sm": "var(--font-size-fluid-sm)",
        "base": "var(--font-size-fluid-base)",
        "lg": "var(--font-size-fluid-lg)",
        "xl": "var(--font-size-fluid-xl)",
        "2xl": "var(--font-size-fluid-2xl)",
        "3xl": "var(--font-size-fluid-3xl)",
        "4xl": "var(--font-size-fluid-4xl)",
        "5xl": "var(--font-size-fluid-5xl)"
      }
    },
    "weight": {
      "thin": "var(--font-weight-thin)",
      "extralight": "var(--font-weight-extralight)",
      "light": "var(--font-weight-light)",
      "normal": "var(--font-weight-normal)",
      "medium": "var(--font-weight-medium)",
      "semibold": "var(--font-weight-semibold)",
      "bold": "var(--font-weight-bold)",
      "extrabold": "var(--font-weight-extrabold)",
      "black": "var(--font-weight-black)"
    }
  },
  "line": {
    "height": {
      "none": "var(--line-height-none)",
      "tight": "var(--line-height-tight)",
      "snug": "var(--line-height-snug)",
      "normal": "var(--line-height-normal)",
      "relaxed": "var(--line-height-relaxed)",
      "loose": "var(--line-height-loose)"
    }
  },
  "letter": {
    "spacing": {
      "tighter": "var(--letter-spacing-tighter)",
      "tight": "var(--letter-spacing-tight)",
      "normal": "var(--letter-spacing-normal)",
      "wide": "var(--letter-spacing-wide)",
      "wider": "var(--letter-spacing-wider)",
      "widest": "var(--letter-spacing-widest)"
    }
  },
  "spacing": {
    "0": {
      "5": "var(--spacing-0-5)",
      "DEFAULT": "var(--spacing-0)"
    },
    "1": {
      "5": "var(--spacing-1-5)",
      "DEFAULT": "var(--spacing-1)"
    },
    "2": {
      "5": "var(--spacing-2-5)",
      "DEFAULT": "var(--spacing-2)"
    },
    "3": {
      "5": "var(--spacing-3-5)",
      "DEFAULT": "var(--spacing-3)"
    },
    "4": "var(--spacing-4)",
    "5": "var(--spacing-5)",
    "6": "var(--spacing-6)",
    "7": "var(--spacing-7)",
    "8": "var(--spacing-8)",
    "9": "var(--spacing-9)",
    "10": "var(--spacing-10)",
    "11": "var(--spacing-11)",
    "12": "var(--spacing-12)",
    "14": "var(--spacing-14)",
    "16": "var(--spacing-16)",
    "20": "var(--spacing-20)",
    "24": "var(--spacing-24)",
    "28": "var(--spacing-28)",
    "32": "var(--spacing-32)",
    "px": "var(--spacing-px)"
  },
  "space": {
    "fluid": {
      "xs": "var(--space-fluid-xs)",
      "sm": "var(--space-fluid-sm)",
      "md": "var(--space-fluid-md)",
      "lg": "var(--space-fluid-lg)",
      "xl": "var(--space-fluid-xl)",
      "2xl": "var(--space-fluid-2xl)",
      "3xl": "var(--space-fluid-3xl)"
    },
    "container": {
      "xs": "var(--space-container-xs)",
      "sm": "var(--space-container-sm)",
      "md": "var(--space-container-md)",
      "lg": "var(--space-container-lg)",
      "xl": "var(--space-container-xl)"
    }
  },
  "shadow": {
    "none": "var(--shadow-none)",
    "sm": "var(--shadow-sm)",
    "base": "var(--shadow-base)",
    "md": "var(--shadow-md)",
    "lg": "var(--shadow-lg)",
    "xl": "var(--shadow-xl)",
    "2xl": "var(--shadow-2xl)",
    "inner": "var(--shadow-inner)"
  },
  "elevation": {
    "0": "var(--elevation-0)",
    "1": "var(--elevation-1)",
    "2": "var(--elevation-2)",
    "3": "var(--elevation-3)",
    "4": "var(--elevation-4)"
  },
  "radius": {
    "none": "var(--radius-none)",
    "sm": "var(--radius-sm)",
    "base": "var(--radius-base)",
    "md": "var(--radius-md)",
    "lg": "var(--radius-lg)",
    "xl": "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
    "3xl": "var(--radius-3xl)",
    "full": "var(--radius-full)"
  },
  "duration": {
    "instant": "var(--duration-instant)",
    "fast": "var(--duration-fast)",
    "normal": "var(--duration-normal)",
    "moderate": "var(--duration-moderate)",
    "slow": "var(--duration-slow)",
    "slower": "var(--duration-slower)",
    "slowest": "var(--duration-slowest)"
  },
  "delay": {
    "none": "var(--delay-none)",
    "xs": "var(--delay-xs)",
    "sm": "var(--delay-sm)",
    "md": "var(--delay-md)",
    "lg": "var(--delay-lg)",
    "xl": "var(--delay-xl)"
  },
  "easing": {
    "linear": "var(--easing-linear)",
    "ease": {
      "DEFAULT": "var(--easing-ease)",
      "in": {
        "DEFAULT": "var(--easing-ease-in)",
        "out": "var(--easing-ease-in-out)"
      },
      "out": "var(--easing-ease-out)"
    },
    "standard": "var(--easing-standard)",
    "decelerate": "var(--easing-decelerate)",
    "accelerate": "var(--easing-accelerate)",
    "spring": "var(--easing-spring)",
    "bounce": "var(--easing-bounce)",
    "elastic": "var(--easing-elastic)",
    "smooth": "var(--easing-smooth)",
    "silk": "var(--easing-silk)"
  },
  "transition": {
    "fast": "var(--transition-fast)",
    "normal": "var(--transition-normal)",
    "slow": "var(--transition-slow)",
    "spring": "var(--transition-spring)",
    "silk": "var(--transition-silk)",
    "colors": {
      "DEFAULT": "var(--transition-colors)",
      "fast": "var(--transition-colors-fast)"
    },
    "transform": {
      "DEFAULT": "var(--transition-transform)",
      "spring": "var(--transition-transform-spring)"
    },
    "opacity": "var(--transition-opacity)",
    "shadow": "var(--transition-shadow)",
    "all": {
      "fast": "var(--transition-all-fast)"
    },
    "scale": {
      "spring": "var(--transition-scale-spring)"
    }
  },
  "motion": {
    "spring": {
      "bouncy": "var(--motion-spring-bouncy)",
      "tight": "var(--motion-spring-tight)"
    }
  },
  "material": {
    "glass": {
      "thin": "var(--material-glass-thin)",
      "regular": "var(--material-glass-regular)",
      "thick": "var(--material-glass-thick)",
      "blur": {
        "sm": "var(--material-glass-blur-sm)",
        "md": "var(--material-glass-blur-md)",
        "lg": "var(--material-glass-blur-lg)"
      },
      "border": "var(--material-glass-border)"
    },
    "surface": {
      "raised": "var(--material-surface-raised)"
    }
  },
  "container": {
    "sm": "var(--container-sm)",
    "md": "var(--container-md)",
    "lg": "var(--container-lg)",
    "xl": "var(--container-xl)",
    "2xl": "var(--container-2xl)"
  },
  "layout": {
    "header": {
      "height": "var(--layout-header-height)"
    },
    "nav": {
      "width": "var(--layout-nav-width)"
    },
    "footer": {
      "height": "var(--layout-footer-height)"
    }
  },
  "bg": {
    "gradient": {
      "primary": "var(--bg-gradient-primary)",
      "secondary": "var(--bg-gradient-secondary)",
      "dark": "var(--bg-gradient-dark)"
    }
  },
  "page": {
    "gradient": {
      "energetic": "var(--page-gradient-energetic)"
    }
  },
  "surface": {
    "strength": {
      "bg": "var(--surface-strength-bg)",
      "foreground": "var(--surface-strength-foreground)",
      "ring": "var(--surface-strength-ring)"
    },
    "recovery": {
      "bg": "var(--surface-recovery-bg)",
      "foreground": "var(--surface-recovery-foreground)",
      "ring": "var(--surface-recovery-ring)"
    },
    "speed": {
      "bg": "var(--surface-speed-bg)",
      "foreground": "var(--surface-speed-foreground)",
      "ring": "var(--surface-speed-ring)"
    },
    "mobility": {
      "bg": "var(--surface-mobility-bg)",
      "foreground": "var(--surface-mobility-foreground)",
      "ring": "var(--surface-mobility-ring)"
    },
    "focus": {
      "bg": "var(--surface-focus-bg)",
      "foreground": "var(--surface-focus-foreground)",
      "ring": "var(--surface-focus-ring)"
    },
    "card": {
      "overlay": "var(--surface-card-overlay)"
    }
  },
  "z": {
    "dropdown": "var(--z-dropdown)",
    "sticky": "var(--z-sticky)",
    "fixed": "var(--z-fixed)",
    "modal": {
      "backdrop": "var(--z-modal-backdrop)",
      "DEFAULT": "var(--z-modal)"
    },
    "popover": "var(--z-popover)",
    "tooltip": "var(--z-tooltip)"
  }
} as const;

export type DesignTokens = typeof tokens;
