import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TOKENS_FILE = path.join(
  __dirname,
  "../../src/styles/design-tokens-unified.css"
);
const OUTPUT_FILE = path.join(__dirname, "../../src/styles/tokens.ts");

// Helper to convert kebab-case to camelCase
const toCamelCase = (str) => {
  return str.replace(/-([a-z0-9])/g, (g) => g[1].toUpperCase());
};

const generateTokens = () => {
  console.log("🎨 Generating type-safe design tokens from unified CSS file...");

  const tokens = {};
  const content = fs.readFileSync(TOKENS_FILE, "utf8");

  // Simple regex to capture CSS variables
  // Matches: --variable-name: value;
  const varRegex = /--([a-zA-Z0-9-]+):\s*([^;]+);/g;

  let match;
  while ((match = varRegex.exec(content)) !== null) {
    const [_, name, value] = match;
    const cleanValue = value.trim();

    // Structure the token object
    // e.g. --color-primary -> tokens.color.primary
    const parts = name.split("-");
    let current = tokens;

    parts.forEach((part, index) => {
      const key = toCamelCase(part);

      if (index === parts.length - 1) {
        // We are at the leaf node, trying to set a value
        if (typeof current[key] === "object" && current[key] !== null) {
          // Collision: It's already an object (from a longer variable processed earlier)
          // Assign to DEFAULT
          current[key].DEFAULT = `var(--${name})`;
        } else {
          // Just assign the value
          current[key] = `var(--${name})`;
        }
      } else {
        // We are at an intermediate node
        if (typeof current[key] === "string") {
          // Collision: It's already a string (from a shorter variable processed earlier)
          // Convert to object with DEFAULT
          current[key] = { DEFAULT: current[key] };
        }

        current[key] = current[key] || {};
        current = current[key];
      }
    });
  }

  const fileContent = `/**
 * 🤖 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/dev/generate-tokens.mjs
 * 
 * This file provides type-safe access to your CSS variables.
 * Use these in your style objects or inline styles.
 */

export const tokens = ${JSON.stringify(tokens, null, 2)} as const;

export type DesignTokens = typeof tokens;
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`✅ Tokens generated at: ${OUTPUT_FILE}`);
};

generateTokens();
